### ISSUE TITLE
ML model building 

### ISSUE THREAD

**Issue by Bijay555** [kandelsatish/used_cars#3]
Tasks:

- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #39
- [x] #23

**Comment by kandelsatish** [comment]
@Aljesh-basnet  i think the performance of the model was improved because you encoded whole data before train test split, which might have caused the data leakage because of which model will already have a understanding about the test data and will predict correctly. Model seems to perform well but there is high change the model is not doing well. @Bijay555  can you once review the code.

**Comment by kandelsatish** [comment]
@Bijay555,@Aljesh-basnet  the model performance has improved while using the new clean data set given by @Bijay555. I have trained ANN model with r2_score: 0.5663668609874887, working in model tuning can take us to good accuracy.

**Comment by kandelsatish** [comment]
@Bijay555   and @Aljesh-basnet  please review the code notebook/recomendation_system.ipynb
